### ISSUE TITLE
Chybějící obrázky

### ISSUE THREAD

**Issue by lojzatran** [LuciaSkal/j2w-ukol01#1]
# Současná situace
Na svém webu používáš obrázky, např. https://github.com/LuciaSkal/j2w-ukol01/blob/f69d817cba5e2911763c805ec422dbc7ae17e834/src/main/resources/static/about.html#L13

# Problém
Když si spustím u sebe tvoji web aplikaci na localhost:8080, chybějí tam obrázky.

# Očekávané řešení
Uvidím obrázky i když si spustím web u sebe.

**Comment by LuciaSkal** [comment]
[#b41fe18](https://github.com/LuciaSkal/j2w-ukol01/commit/b41fe18791546d262d754307cc745b9a1ecec7fc)

**Comment by LuciaSkal** [comment]
[#b41fe18](https://github.com/LuciaSkal/j2w-ukol01/commit/b41fe18791546d262d754307cc745b9a1ecec7fc)  pridane obrazky
